// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkk5gCYJ5EfArjRAfC9Op1RESvmUxoqqs',
    appId: '1:254483651184:web:290c46631a3a74ffe3f2b5',
    messagingSenderId: '254483651184',
    projectId: 'join-auth-firebase',
    authDomain: 'join-auth-firebase.firebaseapp.com',
    storageBucket: 'join-auth-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLPUEyXPYe4-Ot6jCojuyBaFy3Hnswq5o',
    appId: '1:254483651184:android:7a36248c2d94419de3f2b5',
    messagingSenderId: '254483651184',
    projectId: 'join-auth-firebase',
    storageBucket: 'join-auth-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPI_GUH86S7sFwrqdLpEA7KVI5DLNdUhI',
    appId: '1:254483651184:ios:3f7a439ee7b4f784e3f2b5',
    messagingSenderId: '254483651184',
    projectId: 'join-auth-firebase',
    storageBucket: 'join-auth-firebase.appspot.com',
    iosClientId: '254483651184-2bp60buavsngtcttrsdnrgv2tv629vfd.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPI_GUH86S7sFwrqdLpEA7KVI5DLNdUhI',
    appId: '1:254483651184:ios:9b9ef48b022152d8e3f2b5',
    messagingSenderId: '254483651184',
    projectId: 'join-auth-firebase',
    storageBucket: 'join-auth-firebase.appspot.com',
    iosClientId: '254483651184-5lherrdkpr4gm2gat169js24t1tkbv7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginWithFirebase.RunnerTests',
  );
}
